package com.mmd.mssp.domain;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="b2b_project")
public class B2BProject {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Basic
	@Column(name="p_code")
	private String pCode;
	
	@Basic
	@Column(name="p_name")
	private String pName;
	
	@Basic
	@Column(name="p_is_bid")
	private Integer pIsBid; //是否投标 0 否  1 是
	
	@Basic
	@Column(name = "p_bid_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date pBidTime;
	
	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="customer_id")
	private CommCustomer customer;
	
	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="business_id")
	private CommBusiness business;
	
	@Basic
	@Column(name="proto")
	private Integer proto;
	
	@Basic
	@Column(name="entrust")
	private Integer entrust;
	
	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="agent_id")
	private CommAgent agent;
	
	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="comm_si")
	private CommAgent commSi;
	
	@Basic
	@Column(name="send_company")
	private String sendCompany;
	
	@Basic
	@Column(name="send_name")
	private String sendName;
	
	@Basic
	@Column(name="send_address")
	private String sendAddress;
	
	@Basic
	@Column(name="send_address1")
	private String sendAddress1;
	
	@Basic
	@Column(name="send_address2")
	private String sendAddress2;
	
	@Basic
	@Column(name="send_zipcode")
	private String sendZipcode;
	
	@Basic
	@Column(name="send_city")
	private String sendCity;
	
	@Basic
	@Column(name="send_province")
	private String sendProvince;
	
	@Basic
	@Column(name="send_country")
	private String sendCountry;
	
	@Basic
	@Column(name="send_phone")
	private String sendPhone;
	
	@Basic
	@Column(name="send_fax")
	private String sendFax;
	
	@Basic
	@Column(name="send_email")
	private String sendEmail;
	
	@Basic
	@Column(name="receive_company")
	private String receiveCompany;
	
	@Basic
	@Column(name="receive_name")
	private String receiveName;
	
	@Basic
	@Column(name="receive_address")
	private String receiveAddress;
	
	@Basic
	@Column(name="receive_address1")
	private String receiveAddress1;
	
	@Basic
	@Column(name="receive_address2")
	private String receiveAddress2;
	
	@Basic
	@Column(name="receive_zipcode")
	private String receiveZipcode;
	
	@Basic
	@Column(name="receive_city")
	private String receiveCity;
	
	@Basic
	@Column(name="receive_province")
	private String receiveProvince;
	
	@Basic
	@Column(name="receive_country")
	private String receiveCountry;
	
	@Basic
	@Column(name="receive_phone")
	private String receivePhone;
	
	@Basic
	@Column(name="receive_fax")
	private String receiveFax;
	
	@Basic
	@Column(name="receive_email")
	private String receiveEmail;
	
	@Basic
	@Column(name = "agent_send_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date agentSendTime;
	
	@Basic
	@Column(name = "customer_receive_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date customerReceiveTime;
	
	
	@Basic
	@Column(name="product_use_info")
	private String productUseInfo;
	
	@Basic
	@Column(name="after_sales_service")
	private String afterSalesService;
	
	@Basic
	@Column(name="remark")
	private String remark;
	
	@Basic
	@Column(name = "apply_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date applyTime;
	
	@Basic
	@Column(name="p_type")
	private Integer pType; //类型 1，一次性申请单 2，长期申请单
	
	
	@Basic
	@Column(name = "price_valid_begin_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date priceValidBeginTime;
	
	@Basic
	@Column(name = "price_valid_end_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date priceValidEndTime;
	
	@Basic
	@Column(name="decision_info")
	private String decisionInfo;
	
	@Basic
	@Column(name="apply_reason")
	private String applyReason;
	
	@Basic
	@Column(name="upload_apply_data")
	private String uploadApplyData;
	
	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="approve_template_id")
	private ApproveTemplate temp;
	
	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="current_process_step")
	private ProcessStep step;
	
	@Basic
	@Column(name="sample_deal")
	private String sampleDeal;
	
	@Basic
	@Column(name="commitment_note")
	private String commitmentNote;
	
	@Basic
	@Column(name="entrust_pic")
	private String entrustPic;
	
	@Basic
	@Column(name="grant_img")
	private String granImg;
	
	@Basic
	@Column(name="upload_verific_imgs")
	private String uploadImgs;
	
	@Basic
	@Column(name="verific_remark")
	private String verificRemark;
	
	@Basic
	@Column(name="is_delete", columnDefinition="INT")
	private Integer isDelete;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getpCode() {
		return pCode;
	}

	public void setpCode(String pCode) {
		this.pCode = pCode;
	}

	public String getpName() {
		return pName;
	}

	public void setpName(String pName) {
		this.pName = pName;
	}

	public Integer getpIsBid() {
		return pIsBid;
	}

	public void setpIsBid(Integer pIsBid) {
		this.pIsBid = pIsBid;
	}

	public Date getpBidTime() {
		return pBidTime;
	}

	public void setpBidTime(Date pBidTime) {
		this.pBidTime = pBidTime;
	}

	public CommCustomer getCustomer() {
		return customer;
	}

	public void setCustomer(CommCustomer customer) {
		this.customer = customer;
	}

	public CommBusiness getBusiness() {
		return business;
	}

	public void setBusiness(CommBusiness business) {
		this.business = business;
	}

	public Integer getProto() {
		return proto;
	}

	public void setProto(Integer proto) {
		this.proto = proto;
	}

	public Integer getEntrust() {
		return entrust;
	}

	public void setEntrust(Integer entrust) {
		this.entrust = entrust;
	}

	public CommAgent getAgent() {
		return agent;
	}

	public void setAgent(CommAgent agent) {
		this.agent = agent;
	}

	public CommAgent getCommSi() {
		return commSi;
	}

	public void setCommSi(CommAgent commSi) {
		this.commSi = commSi;
	}

	public String getSendCompany() {
		return sendCompany;
	}

	public void setSendCompany(String sendCompany) {
		this.sendCompany = sendCompany;
	}

	public String getSendName() {
		return sendName;
	}

	public void setSendName(String sendName) {
		this.sendName = sendName;
	}

	public String getSendAddress() {
		return sendAddress;
	}

	public void setSendAddress(String sendAddress) {
		this.sendAddress = sendAddress;
	}

	public String getSendAddress1() {
		return sendAddress1;
	}

	public void setSendAddress1(String sendAddress1) {
		this.sendAddress1 = sendAddress1;
	}

	public String getSendAddress2() {
		return sendAddress2;
	}

	public void setSendAddress2(String sendAddress2) {
		this.sendAddress2 = sendAddress2;
	}

	public String getSendZipcode() {
		return sendZipcode;
	}

	public void setSendZipcode(String sendZipcode) {
		this.sendZipcode = sendZipcode;
	}

	public String getSendCity() {
		return sendCity;
	}

	public void setSendCity(String sendCity) {
		this.sendCity = sendCity;
	}

	public String getSendProvince() {
		return sendProvince;
	}

	public void setSendProvince(String sendProvince) {
		this.sendProvince = sendProvince;
	}

	public String getSendCountry() {
		return sendCountry;
	}

	public void setSendCountry(String sendCountry) {
		this.sendCountry = sendCountry;
	}

	public String getSendPhone() {
		return sendPhone;
	}

	public void setSendPhone(String sendPhone) {
		this.sendPhone = sendPhone;
	}

	public String getSendFax() {
		return sendFax;
	}

	public void setSendFax(String sendFax) {
		this.sendFax = sendFax;
	}

	public String getSendEmail() {
		return sendEmail;
	}

	public void setSendEmail(String sendEmail) {
		this.sendEmail = sendEmail;
	}

	public String getReceiveCompany() {
		return receiveCompany;
	}

	public void setReceiveCompany(String receiveCompany) {
		this.receiveCompany = receiveCompany;
	}

	public String getReceiveName() {
		return receiveName;
	}

	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	public String getReceiveAddress() {
		return receiveAddress;
	}

	public void setReceiveAddress(String receiveAddress) {
		this.receiveAddress = receiveAddress;
	}

	public String getReceiveAddress1() {
		return receiveAddress1;
	}

	public void setReceiveAddress1(String receiveAddress1) {
		this.receiveAddress1 = receiveAddress1;
	}

	public String getReceiveAddress2() {
		return receiveAddress2;
	}

	public void setReceiveAddress2(String receiveAddress2) {
		this.receiveAddress2 = receiveAddress2;
	}

	public String getReceiveZipcode() {
		return receiveZipcode;
	}

	public void setReceiveZipcode(String receiveZipcode) {
		this.receiveZipcode = receiveZipcode;
	}

	public String getReceiveCity() {
		return receiveCity;
	}

	public void setReceiveCity(String receiveCity) {
		this.receiveCity = receiveCity;
	}

	public String getReceiveProvince() {
		return receiveProvince;
	}

	public void setReceiveProvince(String receiveProvince) {
		this.receiveProvince = receiveProvince;
	}

	public String getReceiveCountry() {
		return receiveCountry;
	}

	public void setReceiveCountry(String receiveCountry) {
		this.receiveCountry = receiveCountry;
	}

	public String getReceivePhone() {
		return receivePhone;
	}

	public void setReceivePhone(String receivePhone) {
		this.receivePhone = receivePhone;
	}

	public String getReceiveFax() {
		return receiveFax;
	}

	public void setReceiveFax(String receiveFax) {
		this.receiveFax = receiveFax;
	}

	public String getReceiveEmail() {
		return receiveEmail;
	}

	public void setReceiveEmail(String receiveEmail) {
		this.receiveEmail = receiveEmail;
	}

	public Date getAgentSendTime() {
		return agentSendTime;
	}

	public void setAgentSendTime(Date agentSendTime) {
		this.agentSendTime = agentSendTime;
	}

	public Date getCustomerReceiveTime() {
		return customerReceiveTime;
	}

	public void setCustomerReceiveTime(Date customerReceiveTime) {
		this.customerReceiveTime = customerReceiveTime;
	}

	public String getProductUseInfo() {
		return productUseInfo;
	}

	public void setProductUseInfo(String productUseInfo) {
		this.productUseInfo = productUseInfo;
	}

	public String getAfterSalesService() {
		return afterSalesService;
	}

	public void setAfterSalesService(String afterSalesService) {
		this.afterSalesService = afterSalesService;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getApplyTime() {
		return applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	public Integer getpType() {
		return pType;
	}

	public void setpType(Integer pType) {
		this.pType = pType;
	}

	public Date getPriceValidBeginTime() {
		return priceValidBeginTime;
	}

	public void setPriceValidBeginTime(Date priceValidBeginTime) {
		this.priceValidBeginTime = priceValidBeginTime;
	}

	public Date getPriceValidEndTime() {
		return priceValidEndTime;
	}

	public void setPriceValidEndTime(Date priceValidEndTime) {
		this.priceValidEndTime = priceValidEndTime;
	}

	public String getDecisionInfo() {
		return decisionInfo;
	}

	public void setDecisionInfo(String decisionInfo) {
		this.decisionInfo = decisionInfo;
	}

	public String getApplyReason() {
		return applyReason;
	}

	public void setApplyReason(String applyReason) {
		this.applyReason = applyReason;
	}

	public String getUploadApplyData() {
		return uploadApplyData;
	}

	public void setUploadApplyData(String uploadApplyData) {
		this.uploadApplyData = uploadApplyData;
	}

	public ApproveTemplate getTemp() {
		return temp;
	}

	public void setTemp(ApproveTemplate temp) {
		this.temp = temp;
	}

	public ProcessStep getStep() {
		return step;
	}

	public void setStep(ProcessStep step) {
		this.step = step;
	}

	public String getSampleDeal() {
		return sampleDeal;
	}

	public void setSampleDeal(String sampleDeal) {
		this.sampleDeal = sampleDeal;
	}

	public String getCommitmentNote() {
		return commitmentNote;
	}

	public void setCommitmentNote(String commitmentNote) {
		this.commitmentNote = commitmentNote;
	}

	public String getEntrustPic() {
		return entrustPic;
	}

	public void setEntrustPic(String entrustPic) {
		this.entrustPic = entrustPic;
	}

	public String getGranImg() {
		return granImg;
	}

	public void setGranImg(String granImg) {
		this.granImg = granImg;
	}

	public String getUploadImgs() {
		return uploadImgs;
	}

	public void setUploadImgs(String uploadImgs) {
		this.uploadImgs = uploadImgs;
	}

	public String getVerificRemark() {
		return verificRemark;
	}

	public void setVerificRemark(String verificRemark) {
		this.verificRemark = verificRemark;
	}

	public Integer getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(Integer isDelete) {
		this.isDelete = isDelete;
	}
}