package com.mmd.mssp.domain;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="comm_agent")
public class CommAgent {
	
	public static int  DELETE = 1;//已删除
	public static int NOT_DELETE=0;//未删除
	
	public static int IR_LEVEL_AGENT=5;//代理商
	public static int IR_LEVLE_STORE=6;//零售店
	public static int IR_LEVEL_SI=7;//二级分销商

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Basic
	@Column(name="store_id")
	private String storeId;

	@Basic
	@Column(name="ir_name")
	private String irName;
	
	@Basic
	@Column(name="p_id", columnDefinition="INT")
	private Integer pId;
	
	@Basic
	@Column(name="ir_level", columnDefinition="INT")
	private Integer irLevel;
	
	@Basic
	@Column(name="score", columnDefinition="INT")
	private Integer score;
	
	@Basic
	@Column(name="verify_status", columnDefinition="INT")
	private Integer verifyStatus;
	
	@Basic
	@Column(name="verify_msg")
	private String verifyMsg;
	
	@Basic
	@Column(name="verify_members", columnDefinition="INT")
	private Integer verifyMembers;
	
	@Basic
	@Column(name = "verify_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date verifytime;
	
	@Basic
	@Column(name = "createtime", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date createtime;
	
	@Basic
	@Column(name = "last_login_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date lastLoginTime;
	
	@Basic
	@Column(name = "close_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date closetime;
	
	@Basic
	@Column(name="ir_status", columnDefinition="INT")
	private Integer irStatus;
	
	@Basic
	@Column(name="contract_status", columnDefinition="INT")
	private Integer contractStatus;
	
	@Basic
	@Column(name="freeze_msg")
	private String freezeMsg;
	
	@Basic
	@Column(name="close_msg")
	private String closeMsg;
	
/*	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="area_id")
	private CommArea commArea;
	*/
	@Basic
	@Column(name="stores_level", columnDefinition="INT")
	private Integer storesLevel;
	
	@Basic
	@Column(name="image_list")
	private String imageList;
	
	@Basic
	@Column(name = "apply_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date applytime;
	
	@Basic
	@Column(name = "freeze_time", columnDefinition = "TIMESTAMP")
	@Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private Date freezeTime;
	
	@Basic
	@Column(name="contract_image_list")
	private String contractImageList;
	
	@Basic
	@Column(name="type", columnDefinition="INT")
	private Integer type;
	
	@Basic
	@Column(name="is_delete", columnDefinition="INT")
	private Integer isDelete;
	
	@OneToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="province_id")
	private CommProvince province;

	@OneToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="city_id")
	private CommCity commCity;
	
	@Basic
	@Column(name="address")
	private String address;
	@Basic
	@Column(name="phone")
	private String phone;
	@Basic
	@Column(name="email")
	private String email;
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStoreId() {
		return storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	public Integer getpId() {
		return pId;
	}

	public Integer getIrLevel() {
		return irLevel;
	}

	public void setIrLevel(Integer irLevel) {
		this.irLevel = irLevel;
	}

	public void setpId(Integer pId) {
		this.pId = pId;
	}

	public Integer getScore() {
		return score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Integer getVerifyStatus() {
		return verifyStatus;
	}

	public void setVerifyStatus(Integer verifyStatus) {
		this.verifyStatus = verifyStatus;
	}

	public String getVerifyMsg() {
		return verifyMsg;
	}

	public void setVerifyMsg(String verifyMsg) {
		this.verifyMsg = verifyMsg;
	}

	public Integer getVerifyMembers() {
		return verifyMembers;
	}

	public void setVerifyMembers(Integer verifyMembers) {
		this.verifyMembers = verifyMembers;
	}

	public Date getVerifytime() {
		return verifytime;
	}

	public void setVerifytime(Date verifytime) {
		this.verifytime = verifytime;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public Date getClosetime() {
		return closetime;
	}

	public void setClosetime(Date closetime) {
		this.closetime = closetime;
	}

	public String getIrName() {
		return irName;
	}

	public void setIrName(String irName) {
		this.irName = irName;
	}

	public Integer getIrStatus() {
		return irStatus;
	}

	public void setIrStatus(Integer irStatus) {
		this.irStatus = irStatus;
	}

	public Integer getContractStatus() {
		return contractStatus;
	}

	public void setContractStatus(Integer contractStatus) {
		this.contractStatus = contractStatus;
	}

	public String getFreezeMsg() {
		return freezeMsg;
	}

	public void setFreezeMsg(String freezeMsg) {
		this.freezeMsg = freezeMsg;
	}

	public String getCloseMsg() {
		return closeMsg;
	}

	public void setCloseMsg(String closeMsg) {
		this.closeMsg = closeMsg;
	}

/*	public CommArea getCommArea() {
		return commArea;
	}

	public void setCommArea(CommArea commArea) {
		this.commArea = commArea;
	}*/

	public Integer getStoresLevel() {
		return storesLevel;
	}

	public void setStoresLevel(Integer storesLevel) {
		this.storesLevel = storesLevel;
	}

	public String getImageList() {
		return imageList;
	}

	public void setImageList(String imageList) {
		this.imageList = imageList;
	}

	public Date getApplytime() {
		return applytime;
	}

	public void setApplytime(Date applytime) {
		this.applytime = applytime;
	}

	public Date getFreezeTime() {
		return freezeTime;
	}

	public void setFreezeTime(Date freezeTime) {
		this.freezeTime = freezeTime;
	}

	public String getContractImageList() {
		return contractImageList;
	}

	public void setContractImageList(String contractImageList) {
		this.contractImageList = contractImageList;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(Integer isDelete) {
		this.isDelete = isDelete;
	}

	public CommCity getCommCity() {
		return commCity;
	}

	public void setCommCity(CommCity commCity) {
		this.commCity = commCity;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public CommProvince getProvince() {
		return province;
	}

	public void setProvince(CommProvince province) {
		this.province = province;
	}
}