package com.mmd.mssp.domain;

import java.util.*;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="comm_permission")
public class CommPermission {
	
	@OneToMany(targetEntity=com.mmd.mssp.domain.CommRolePermission.class, mappedBy="commRole", cascade=CascadeType.MERGE)
	private Set commRolePermission = new HashSet();
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	@Basic
	private String name;

	@Basic
	@Column(name="permission_code")
	private String permissionCode;

	@Basic
	private String url;
	

	public CommPermission() {
	}

	public CommPermission(long id) {
		this.id = id;
	}

	public Set getCommRolePermission() {
		return commRolePermission;
	}

	public void setCommRolePermission(Set commRolePermission) {
		this.commRolePermission = commRolePermission;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPermissionCode() {
		return permissionCode;
	}

	public void setPermissionCode(String permissionCode) {
		this.permissionCode = permissionCode;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
}