package com.mmd.mssp.domain;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="special_apply_product")
public class SpecialApplyProduct {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="product_price_id")
	private ProductPrice productPrice;
	
	@Basic
	@Column(name="apply_price")
	private BigDecimal applyPrice;
	
	@Basic
	@Column(name="number")
	private Integer number;
	
	@Basic
	@Column(name="discount_rate")
	private BigDecimal discountRate;
	
	@Basic
	@Column(name="win_rate")
	private Integer winRate;
	
	@Basic
	@Column(name="remark")
	private String remark;
	
	@Basic
	@Column(name="compete_product")
	private String competeProduct;
	
	@Basic
	@Column(name="compete_price")
	private BigDecimal competePrice;
	
	@Basic
	@Column(name="approve_price")
	private BigDecimal approvePrice;
	
	@Basic
	@Column(name="area_mange_rice")
	private BigDecimal areaMangePrice;
	
	@Basic
	@Column(name="sell_mange_price")
	private BigDecimal sellMangePrice;
	
	@Basic
	@Column(name="industry_mange_price")
	private BigDecimal industryMangePrice;
	
	@ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name="b2b_project_id")
	private B2BProject b2bProject;
	
	@Transient
	private BigDecimal rebate;//返利

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProductPrice getProductPrice() {
		return productPrice;
	}

	public void setProductPrice(ProductPrice productPrice) {
		this.productPrice = productPrice;
	}

	public BigDecimal getApplyPrice() {
		return applyPrice;
	}

	public void setApplyPrice(BigDecimal applyPrice) {
		this.applyPrice = applyPrice;
	}

	public Integer getNumber() {
		return number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public BigDecimal getDiscountRate() {
		return discountRate;
	}

	public void setDiscountRate(BigDecimal discountRate) {
		this.discountRate = discountRate;
	}

	public Integer getWinRate() {
		return winRate;
	}

	public void setWinRate(Integer winRate) {
		this.winRate = winRate;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCompeteProduct() {
		return competeProduct;
	}

	public void setCompeteProduct(String competeProduct) {
		this.competeProduct = competeProduct;
	}

	public BigDecimal getCompetePrice() {
		return competePrice;
	}

	public void setCompetePrice(BigDecimal competePrice) {
		this.competePrice = competePrice;
	}

	public BigDecimal getApprovePrice() {
		return approvePrice;
	}

	public void setApprovePrice(BigDecimal approvePrice) {
		this.approvePrice = approvePrice;
	}

	public B2BProject getB2bProject() {
		return b2bProject;
	}

	public void setB2bProject(B2BProject b2bProject) {
		this.b2bProject = b2bProject;
	}

	public BigDecimal getAreaMangePrice() {
		return areaMangePrice;
	}

	public void setAreaMangePrice(BigDecimal areaMangePrice) {
		this.areaMangePrice = areaMangePrice;
	}

	public BigDecimal getSellMangePrice() {
		return sellMangePrice;
	}

	public void setSellMangePrice(BigDecimal sellMangePrice) {
		this.sellMangePrice = sellMangePrice;
	}

	public BigDecimal getRebate() {
		return rebate;
	}

	public void setRebate(BigDecimal rebate) {
		this.rebate = rebate;
	}

	public BigDecimal getIndustryMangePrice() {
		return industryMangePrice;
	}

	public void setIndustryMangePrice(BigDecimal industryMangePrice) {
		this.industryMangePrice = industryMangePrice;
	}
	
}