package com.mmd.mssp.domain.vo;

import java.util.LinkedHashMap;
import java.util.Map;

public class TitleMapper {
	static{
		Map mapper = new LinkedHashMap();
		mapper.put("productName","产品型号");
		mapper.put("totalSellIn", "sellIn");
		mapper.put("totalSellOut", "sellOut");
		mapper.put("currentInventory", "库存");
		mapper.put("city", "城市");
		mapper.put("size1", "寸别");
		mapper.put("size2", "寸别-2");
		mapper.put("pannel", "面板");
		mapper.put("channelType", "出货渠道");
		psiReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("area", "区域");
		mapper.put("agent", "代理商");
		mapper.put("type", "项目类别");
		mapper.put("pCode", "文件编号");
		mapper.put("condition", "考核条件或目标");
		mapper.put("content", "申请项目内容");
		mapper.put("product", "型号/项目");
		mapper.put("applyPrice", "支持单台价格（元）");
		mapper.put("number", "数量");
		mapper.put("isPicking", "是否以实际提货量计算");
		mapper.put("poPrice", "开票价");
		mapper.put("netPrice", "NET价");
		mapper.put("financePrice", "财报价");
		mapper.put("syPrice", "单台损益");
		mapper.put("isGrowth", "零售型号是否环比增长");
		mapper.put("growthRate", "零售型号环比增长率");
		mapper.put("applyTotalPrice", "申请支持总金额");
		mapper.put("compProduct", "竞品型号");
		mapper.put("compPrice", "竞品价格");
		mapper.put("remark", "备注");
		b2cReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("city", "城市");
		mapper.put("pCode", "项目编号");
		mapper.put("pName", "项目名称");
		mapper.put("approveStatus", "状态");//状态、核销状态、返利状态都对应process_step表的operate_status字段
		mapper.put("SIName", "SI名称");
		mapper.put("SIPhone", "SI电话");
		//mapper.put("SI", "SI联系人");
		mapper.put("SIAddress", "SI地址");
		mapper.put("customerName", "客户名称");
		mapper.put("product", "申请型号");
		mapper.put("number", "申请台数");
		mapper.put("size1", "型号尺寸");
		mapper.put("applyPrice", "申请价格");
		mapper.put("approvePrice", "批复价格");//其实就是申请价格，当审批后就是批复价格，数据库中和申请价格对应同一字段
		mapper.put("applyTime", "申请日期");
		//mapper.put("compPrice", "预计采购时间");
		mapper.put("customerAddress", "客户地址");
		mapper.put("customerLinkman", "客户联系人");
		mapper.put("customerPhone", "客户电话");
		//mapper.put("compPrice", "客户手机");
		mapper.put("approveMsg", "全国经理审核意见");
		mapper.put("approveTime", "全国经理审批时间");
		mapper.put("hxStatus", "核销状态");
		mapper.put("flStatus", "返利状态");
		b2bReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("city", "城市");
		mapper.put("pCode", "项目编号");
		mapper.put("pName", "项目名称");
		mapper.put("approveStatus", "状态");
		mapper.put("customerName", "客户名称");
		mapper.put("SIName", "SI名称");
		mapper.put("SIPhone", "SI电话");
		mapper.put("product", "申请型号");
		mapper.put("number", "申请台数");
		mapper.put("size1", "型号尺寸");
		mapper.put("applyPrice", "申请价格");
		mapper.put("approvePrice", "批复价格");
		mapper.put("applyTime", "申请日期");
		mapper.put("customerAddress", "客户地址");
		mapper.put("customerLinkman", "客户联系人");
		mapper.put("customerPhone", "客户电话");
		mapper.put("approveMsg", "全国经理审核意见");
		mapper.put("approveTime", "全国经理审批时间");
		mapper.put("hxStatus", "核销状态");
		mapper.put("flStatus", "返利状态");
		b2iReportMapper = mapper;
		//irtail报表
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("chargesDetail", "费用明细");
		mapper.put("cityLevel", "中心城市");
		mapper.put("decorateLevel", "装修类型");
		mapper.put("iAcreage", "店面面积");
		mapper.put("iLevel", "店面级别");
		mapper.put("iLocation", "店面位置");
		mapper.put("iName", "零售店名称");
		mapper.put("iPrincipal", "店负责人");
		mapper.put("iRealPic", "实景图");
		mapper.put("iResultPic", "效果图");
		mapper.put("iTargetVolume", "门店目标量");
		mapper.put("lsRate", "月零售产品占比");
		mapper.put("lsVolume", "月零售产品销量");
		mapper.put("phone", "联系手机");
		mapper.put("remark", "情况说明");
		mapper.put("shopPlace", "卖场名称");
		mapper.put("yqVolume", "月全产品销量");
		mapper.put("material", "物料");
		mapper.put("operateStatus", "状态");
		r01ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("samleContent", "样机内容");
		mapper.put("operateStatus", "状态");
		r02ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("AOCMoney", "[AOC]金额");
		mapper.put("AOCtoreCount", "[AOC]店数");
		mapper.put("ASUSMoney", "[ASUS]金额");
		mapper.put("ASUStoreCount", "[ASUS]店数");
		mapper.put("MMInvest", "MM投入");
		mapper.put("PH", "PH");
		mapper.put("SSMoney", "[SS]金额");
		mapper.put("SSStoreCount", "[SS]店数");
		mapper.put("agentInvest", "代理商投入");
		mapper.put("retailStore", "零售店");//零售店及年预估销量
		mapper.put("storeAddress", "卖场地址");
		mapper.put("storeName", "卖场名称");
		mapper.put("totalInvest", "总投入");
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r03ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("iResultPic", "效果图");
		mapper.put("moneySum", "宣传品数量");
		mapper.put("price", "制作单价");
		mapper.put("propagandaCount", "宣传品数量");
		mapper.put("propagandaLevel", "宣传品类型");
		mapper.put("propagandaSize", "宣传品尺寸");
		mapper.put("propagandaTheme", "宣传品主题");
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r04ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("chargesDetail", "费用明细");
		mapper.put("meetingPerNum", "会议人数");
		mapper.put("meetingPlace", "会议地点");
		mapper.put("meetingProcess", "会议流程");
		mapper.put("others", "其他");
		mapper.put("travelProcess", "旅游行程");
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r05ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("IDCardNumber", "身份证号");
		mapper.put("basePay", "基本工资");
		mapper.put("bonus", "奖金");
		mapper.put("monthProductSale", "零售店名称");
		mapper.put("monthRetailSale", "月零售产品总销量");
		mapper.put("name", "促销员姓名");
		mapper.put("phone", "联系手机");
		mapper.put("retailName", "零售店名称");
		mapper.put("retailProductPercent", "月零售产品占比");
		mapper.put("salerMarkContent", "促销员打分备注");
		mapper.put("salerMarkUrl", "促销员打分");
		mapper.put("salerPhotoContent", "促销员照片备注");
		mapper.put("salerPhotoUrl", "促销员照片");
		mapper.put("totalSalary", "工资总计");
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r06ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("发布费用", "发布费用");
		mapper.put("媒体名称", "媒体名称");
		mapper.put("媒体性质", "媒体性质");
		mapper.put("广告尺寸", "广告尺寸");
		mapper.put("效果图url", "效果图");
		mapper.put("情况说明", "情况说明");
		mapper.put("operateStatus", "状态");
		r07ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("人员费用", "人员费用");
		mapper.put("卖场名称", "卖场名称");
		mapper.put("场地位置", "场地位置");
		mapper.put("场租费用", "场租费用");
		mapper.put("实景图url", "实景图");
		mapper.put("搭建费用", "搭建费用");
		mapper.put("活动期间零售产品销量", "活动期间零售产品销量");
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r08ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("促销型号", "促销型号");
		mapper.put("实际销量", "实际销量");
		mapper.put("计划销量", "计划销量");
		mapper.put("赠品全额", "赠品全额");
		mapper.put("赠品单价", "赠品单价");
		mapper.put("赠品名称", "赠品名称");
		mapper.put("赠品数量", "赠品数量");
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r09ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		//mapper.put("applyContent", "申请内容");R10申请内容待定
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r10ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		mapper.put("下单人姓名", "下单人姓名");
		mapper.put("下单时间", "下单时间");
		mapper.put("产品积分", "产品积分");
		mapper.put("商品单价", "商品单价");
		mapper.put("商品名称", "商品名称");
		mapper.put("商品数量", "商品数量");
		mapper.put("当月代理成本价", "当月代理成本价");
		mapper.put("订单状态", "订单状态");
		mapper.put("订单积分", "订单积分");
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r11ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("province", "所属省份");
		mapper.put("ppn", "申请编号");
		mapper.put("agent", "代理商");
		mapper.put("applyTheme", "申请主题");
		mapper.put("applyDate", "申请日期");
		mapper.put("applyPrice", "申请费用");
		mapper.put("beginTime", "有效期开始时间");
		mapper.put("endTime", "有效期结束时间");
		mapper.put("provider", "供应商");
		mapper.put("approveEmail", "特批邮件");
		//mapper.put("applyContent", "申请内容");R12申请内容待定
		mapper.put("remark", "情况说明");
		mapper.put("operateStatus", "状态");
		r12ReportMapper = mapper;
		
		mapper = new LinkedHashMap();
		mapper.put("size", "代理商");
		mapper.put("series", "申请编号");
		mapper.put("product", "代理商");
		mapper.put("comment", "申请主题");
		mapper.put("next", "代理商下个月需求");
		mapper.put("nnext", "代理商下下个月需求");
		estReportMapper = mapper;
	}
	public static Map<String,String> psiReportMapper;
	public static Map<String,String> b2cReportMapper;
	public static Map<String,String> b2bReportMapper;
	public static Map<String,String> b2iReportMapper;
	public static Map<String,String> r01ReportMapper;
	public static Map<String,String> r02ReportMapper;
	public static Map<String,String> r03ReportMapper;
	public static Map<String,String> r04ReportMapper;
	public static Map<String,String> r05ReportMapper;
	public static Map<String,String> r06ReportMapper;
	public static Map<String,String> r07ReportMapper;
	public static Map<String,String> r08ReportMapper;
	public static Map<String,String> r09ReportMapper;
	public static Map<String,String> r10ReportMapper;
	public static Map<String,String> r11ReportMapper;
	public static Map<String,String> r12ReportMapper;
	public static Map<String,String> estReportMapper;
}
